# default setting

# LOGGING
logging:
  config: classpath:logback-spring.xml

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 7788


---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.250:3306/wmp
    username: wmp
    password: 1q2w3e4r5t
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8008


